name: typo3-autoloader
services:
  appservice:
    type: php:7.3
    via: cli
    xdebug: 'debug,develop'
    composer_version: '2.1.9'
    run:
      - composer install
    config:
      php: .lando/config/php/php.ini
tooling:
  composer:
    service: appservice
  xdebug-on-request:
    service: appservice
    description: Start xdebug with request
    cmd: sed -i 's/xdebug.start_with_request=no/xdebug.start_with_request=yes/g' /app/.lando/config/php/php.ini
  xdebug-off-request:
    service: appservice
    description: Do not start xdebug with request
    cmd: sed -i 's/xdebug.start_with_request=yes/xdebug.start_with_request=no/g' /app/.lando/config/php/php.ini
  pre-commit:
    description: Run pre commit commands
    service: appservice
    cmd: composer code:check
